name: Deploy Sphinx site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx PDF
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk tex-gyre
          sphinx-build -M latexpdf docs docs/_build/latex
#          cd docs/
#          make latexpdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/latex/*.pdf

